// <auto-generated />
namespace CampingDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CampingPlacetoSightseeing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CampingPlacetoSightseeing));
        
        string IMigrationMetadata.Id
        {
            get { return "201702121850125_CampingPlace-to-Sightseeing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
